version: '3'

services:
  flask:
    build: .
    command: "flask run --host=0.0.0.0"
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
